apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-config
  namespace: risk-platform
data:
  LOG_LEVEL: "info"
  GRPC_ADDR: ":50058"
  METRICS_ADDR: ":9098"
  REDIS_ADDR: "redis.infra.svc.cluster.local:6379"
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector.infra.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "workflow"
  OTEL_ENVIRONMENT: "production"
