apiVersion: v1
kind: Service
metadata:
  name: workflow
  namespace: risk-platform
spec:
  selector:
    app: workflow
  ports:
    - name: grpc
      port: 50058
      targetPort: 50058
    - name: metrics
      port: 9098
      targetPort: 9098
  type: ClusterIP
