apiVersion: v1
kind: Service
metadata:
  name: ingestion
  namespace: risk-platform
spec:
  selector:
    app: ingestion
  ports:
    - name: grpc
      port: 50053
      targetPort: 50053
    - name: metrics
      port: 9093
      targetPort: 9093
  type: ClusterIP
