apiVersion: v1
kind: Service
metadata:
  name: graphql-bff
  namespace: risk-platform
spec:
  selector:
    app: graphql-bff
  ports:
    - name: http
      port: 8090
      targetPort: 8090
    - name: metrics
      port: 9104
      targetPort: 9104
  type: ClusterIP
