package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"time"

	casemanagementpb "graphql-bff/api/gen/case-management"
	audittrailpb "graphql-bff/api/gen/audit-trail"
	decisionpb "graphql-bff/api/gen/decision"
	ingestion "graphql-bff/api/gen/ingestion"
	notificationpb "graphql-bff/api/gen/notification"
	opsquerypb "graphql-bff/api/gen/ops-query"
	rulesengine "graphql-bff/api/gen/rules-engine"
	tenantpb "graphql-bff/api/gen/tenant"
	workflowpb "graphql-bff/api/gen/workflow"
	"graphql-bff/graph/generated"
	"graphql-bff/graph/model"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	otelmetric "go.opentelemetry.io/otel/metric"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// ══════════════════════════════════════════════════════════════════════════════
// MUTATION RESOLVERS
// ══════════════════════════════════════════════════════════════════════════════

// IngestPayment is the resolver for the ingestPayment field.
func (r *mutationResolver) IngestPayment(ctx context.Context, input model.IngestPaymentInput) (*model.IngestionResult, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.IngestPayment")
	defer span.End()

	result, err := r.Clients.Ingestion.IngestPayment(ctx, &ingestion.IngestPaymentRequest{
		IdempotencyKey: input.IdempotencyKey,
		TenantId:       input.TenantID,
		Amount:         int64(input.Amount),
		Currency:       input.Currency,
		Source:         input.Source,
		Destination:    input.Destination,
	})
	if err != nil {
		return nil, err
	}
	r.Metrics.MutationTotal.Add(ctx, 1, withAttr("operation", "IngestPayment"))
	return &model.IngestionResult{
		EventID: result.EventId,
		Status:  mapPaymentStatus(result.Status),
		Reason:  result.Reason,
	}, nil
}

// OverrideDecision is the resolver for the overrideDecision field.
func (r *mutationResolver) OverrideDecision(ctx context.Context, input model.OverrideDecisionInput) (string, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.OverrideDecision")
	defer span.End()

	overrideID, err := r.Clients.Decision.OverrideDecision(ctx,
		input.DecisionID, input.AnalystID,
		mapOutcomeToProto(input.NewOutcome),
		input.Reason,
	)
	if err != nil {
		return "", err
	}
	r.Metrics.MutationTotal.Add(ctx, 1, withAttr("operation", "OverrideDecision"))
	return overrideID, nil
}

// CreateCase is the resolver for the createCase field.
func (r *mutationResolver) CreateCase(ctx context.Context, input model.CreateCaseInput) (*model.Case, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.CreateCase")
	defer span.End()

	c, err := r.Clients.CaseMgmt.CreateCase(ctx, &casemanagementpb.CreateCaseRequest{
		DecisionId:     input.DecisionID,
		TenantId:       input.TenantID,
		PaymentEventId: input.PaymentEventID,
		Outcome:        input.Outcome,
		Priority:       mapCasePriorityToProto(input.Priority),
	})
	if err != nil {
		return nil, err
	}
	r.Metrics.MutationTotal.Add(ctx, 1, withAttr("operation", "CreateCase"))
	return protoToCase(c), nil
}

// AssignCase is the resolver for the assignCase field.
func (r *mutationResolver) AssignCase(ctx context.Context, input model.AssignCaseInput) (*model.Case, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.AssignCase")
	defer span.End()

	c, err := r.Clients.CaseMgmt.AssignCase(ctx, &casemanagementpb.AssignCaseRequest{
		CaseId:     input.CaseID,
		AssigneeId: input.AssigneeID,
		ActorId:    input.ActorID,
	})
	if err != nil {
		return nil, err
	}
	r.Metrics.MutationTotal.Add(ctx, 1, withAttr("operation", "AssignCase"))
	return protoToCase(c), nil
}

// UpdateCaseStatus is the resolver for the updateCaseStatus field.
func (r *mutationResolver) UpdateCaseStatus(ctx context.Context, input model.UpdateCaseStatusInput) (*model.Case, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.UpdateCaseStatus")
	defer span.End()

	c, err := r.Clients.CaseMgmt.UpdateCaseStatus(ctx, &casemanagementpb.UpdateCaseStatusRequest{
		CaseId:  input.CaseID,
		Status:  mapCaseStatusToProto(input.Status),
		ActorId: input.ActorID,
		Notes:   input.Notes,
	})
	if err != nil {
		return nil, err
	}
	r.Metrics.MutationTotal.Add(ctx, 1, withAttr("operation", "UpdateCaseStatus"))
	return protoToCase(c), nil
}

// EscalateCase is the resolver for the escalateCase field.
func (r *mutationResolver) EscalateCase(ctx context.Context, input model.EscalateCaseInput) (*model.Case, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.EscalateCase")
	defer span.End()

	c, err := r.Clients.CaseMgmt.EscalateCase(ctx, &casemanagementpb.EscalateCaseRequest{
		CaseId:  input.CaseID,
		ActorId: input.ActorID,
		Reason:  input.Reason,
	})
	if err != nil {
		return nil, err
	}
	r.Metrics.MutationTotal.Add(ctx, 1, withAttr("operation", "EscalateCase"))
	return protoToCase(c), nil
}

// CreateWorkflowTemplate is the resolver for the createWorkflowTemplate field.
func (r *mutationResolver) CreateWorkflowTemplate(ctx context.Context, input model.CreateWorkflowTemplateInput) (*model.WorkflowTemplate, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.CreateWorkflowTemplate")
	defer span.End()

	transitions := make([]*workflowpb.Transition, len(input.Transitions))
	for i, t := range input.Transitions {
		transitions[i] = &workflowpb.Transition{
			FromState:    t.FromState,
			ToState:      t.ToState,
			RequiredRole: t.RequiredRole,
		}
	}

	tmpl, err := r.Clients.Workflow.CreateTemplate(ctx, &workflowpb.CreateWorkflowTemplateRequest{
		TenantId:    input.TenantID,
		Name:        input.Name,
		States:      input.States,
		Transitions: transitions,
	})
	if err != nil {
		return nil, err
	}
	r.Metrics.MutationTotal.Add(ctx, 1, withAttr("operation", "CreateWorkflowTemplate"))
	return protoToWorkflowTemplate(tmpl), nil
}

// UpdateWorkflowTemplate is the resolver for the updateWorkflowTemplate field.
func (r *mutationResolver) UpdateWorkflowTemplate(ctx context.Context, input model.UpdateWorkflowTemplateInput) (*model.WorkflowTemplate, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.UpdateWorkflowTemplate")
	defer span.End()

	transitions := make([]*workflowpb.Transition, len(input.Transitions))
	for i, t := range input.Transitions {
		transitions[i] = &workflowpb.Transition{
			FromState:    t.FromState,
			ToState:      t.ToState,
			RequiredRole: t.RequiredRole,
		}
	}

	tmpl, err := r.Clients.Workflow.UpdateTemplate(ctx, &workflowpb.UpdateWorkflowTemplateRequest{
		TemplateId:  input.TemplateID,
		TenantId:    input.TenantID,
		States:      input.States,
		Transitions: transitions,
	})
	if err != nil {
		return nil, err
	}
	r.Metrics.MutationTotal.Add(ctx, 1, withAttr("operation", "UpdateWorkflowTemplate"))
	return protoToWorkflowTemplate(tmpl), nil
}

// EvaluateTransition is the resolver for the evaluateTransition field.
func (r *mutationResolver) EvaluateTransition(ctx context.Context, input model.EvaluateTransitionInput) (*model.TransitionResult, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.EvaluateTransition")
	defer span.End()

	allowed, reason, err := r.Clients.Workflow.EvaluateTransition(ctx, &workflowpb.EvaluateTransitionRequest{
		TemplateId: input.TemplateID,
		TenantId:   input.TenantID,
		FromState:  input.FromState,
		ToState:    input.ToState,
		ActorRole:  input.ActorRole,
	})
	if err != nil {
		return nil, err
	}
	return &model.TransitionResult{Allowed: allowed, Reason: reason}, nil
}

// CreateRule is the resolver for the createRule field.
func (r *mutationResolver) CreateRule(ctx context.Context, input model.CreateRuleInput) (*model.Rule, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.CreateRule")
	defer span.End()

	rule, err := r.Clients.Rules.CreateRule(ctx,
		input.TenantID, input.Name, input.Expression,
		mapRuleActionToProto(input.Action),
		int32(input.Priority),
	)
	if err != nil {
		return nil, err
	}
	r.Metrics.MutationTotal.Add(ctx, 1, withAttr("operation", "CreateRule"))
	return protoToRule(rule), nil
}

// UpdateRule is the resolver for the updateRule field.
func (r *mutationResolver) UpdateRule(ctx context.Context, input model.UpdateRuleInput) (*model.Rule, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.UpdateRule")
	defer span.End()

	rule, err := r.Clients.Rules.UpdateRule(ctx,
		input.RuleID, input.TenantID, input.Expression,
		mapRuleActionToProto(input.Action),
		int32(input.Priority),
		input.Enabled,
	)
	if err != nil {
		return nil, err
	}
	r.Metrics.MutationTotal.Add(ctx, 1, withAttr("operation", "UpdateRule"))
	return protoToRule(rule), nil
}

// DeleteRule is the resolver for the deleteRule field.
func (r *mutationResolver) DeleteRule(ctx context.Context, input model.DeleteRuleInput) (bool, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.DeleteRule")
	defer span.End()

	return r.Clients.Rules.DeleteRule(ctx, input.RuleID, input.TenantID)
}

// SimulateRule is the resolver for the simulateRule field.
func (r *mutationResolver) SimulateRule(ctx context.Context, input model.SimulateRuleInput) (*model.RuleEvalResult, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.SimulateRule")
	defer span.End()

	expr, err := r.Clients.Rules.SimulateRule(ctx, &rulesengine.SimulateRuleRequest{
		TenantId: input.TenantID,
		RuleId:   input.RuleID,
		Action:   mapRuleActionToProto(input.Action),
		Context: &rulesengine.PaymentContext{
			PaymentEventId: input.PaymentEventID,
			TenantId:       input.TenantID,
			Amount:         int64(input.Amount),
			Currency:       input.Currency,
			Source:         input.Source,
			Destination:    input.Destination,
		},
	})
	if err != nil {
		return nil, err
	}
	return &model.RuleEvalResult{
		RuleID:   expr.RuleId,
		RuleName: expr.RuleName,
		Matched:  expr.Matched,
		Action:   mapRuleAction(expr.Action),
		Reason:   expr.Reason,
	}, nil
}

// CreateTenant is the resolver for the createTenant field.
func (r *mutationResolver) CreateTenant(ctx context.Context, input model.CreateTenantInput) (*model.Tenant, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.CreateTenant")
	defer span.End()

	t, err := r.Clients.Tenant.CreateTenant(ctx, input.Name, &tenantpb.TenantConfig{
		RuleSetId:          input.RuleSetID,
		WorkflowTemplateId: input.WorkflowTemplateID,
	})
	if err != nil {
		return nil, err
	}
	r.Metrics.MutationTotal.Add(ctx, 1, withAttr("operation", "CreateTenant"))
	return protoToTenant(t), nil
}

// UpdateTenantRuleConfig is the resolver for the updateTenantRuleConfig field.
func (r *mutationResolver) UpdateTenantRuleConfig(ctx context.Context, input model.UpdateTenantRuleConfigInput) (*model.Tenant, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.UpdateTenantRuleConfig")
	defer span.End()

	t, err := r.Clients.Tenant.UpdateTenantRuleConfig(ctx, input.TenantID, input.RuleSetID)
	if err != nil {
		return nil, err
	}
	return protoToTenant(t), nil
}

// UpdateTenantWorkflowConfig is the resolver for the updateTenantWorkflowConfig field.
func (r *mutationResolver) UpdateTenantWorkflowConfig(ctx context.Context, input model.UpdateTenantWorkflowConfigInput) (*model.Tenant, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.UpdateTenantWorkflowConfig")
	defer span.End()

	t, err := r.Clients.Tenant.UpdateTenantWorkflowConfig(ctx, input.TenantID, input.WorkflowTemplateID)
	if err != nil {
		return nil, err
	}
	return protoToTenant(t), nil
}

// SendNotification is the resolver for the sendNotification field.
func (r *mutationResolver) SendNotification(ctx context.Context, input model.SendNotificationInput) (*model.NotificationSendResult, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.SendNotification")
	defer span.End()

	id, status, err := r.Clients.Notification.Send(ctx, &notificationpb.SendNotificationRequest{
		TenantId:  input.TenantID,
		Type:      input.Type,
		Recipient: input.Recipient,
		Channel:   mapNotificationChannelToProto(input.Channel),
		Payload:   input.Payload,
	})
	if err != nil {
		return nil, err
	}
	return &model.NotificationSendResult{
		NotificationID: id,
		Status:         mapNotificationStatus(status),
	}, nil
}

// UpdateNotificationPreferences is the resolver for the updateNotificationPreferences field.
func (r *mutationResolver) UpdateNotificationPreferences(ctx context.Context, input model.UpdateNotificationPreferencesInput) (*model.NotificationPreference, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.UpdateNotificationPreferences")
	defer span.End()

	pref, err := r.Clients.Notification.UpdatePreferences(ctx, &notificationpb.UpdateNotificationPreferencesRequest{
		TenantId:  input.TenantID,
		Channel:   mapNotificationChannelToProto(input.Channel),
		EventType: input.EventType,
		Enabled:   input.Enabled,
		Config:    input.Config,
	})
	if err != nil {
		return nil, err
	}
	return protoToNotificationPreference(pref), nil
}

// AppendAuditEvent is the resolver for the appendAuditEvent field.
func (r *mutationResolver) AppendAuditEvent(ctx context.Context, tenantID string, actorID string, action string, resourceType string, resourceID string) (*model.AuditEvent, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "mutation.AppendAuditEvent")
	defer span.End()

	evt, err := r.Clients.Audit.AppendEvent(ctx, &audittrailpb.AppendAuditEventRequest{
		TenantId:     tenantID,
		ActorId:      actorID,
		Action:       action,
		ResourceType: resourceType,
		ResourceId:   resourceID,
		SourceTopic:  "graphql-bff",
	})
	if err != nil {
		return nil, err
	}
	return protoToAuditEvent(evt), nil
}

// ══════════════════════════════════════════════════════════════════════════════
// QUERY RESOLVERS
// ══════════════════════════════════════════════════════════════════════════════

// PaymentEvent is the resolver for the paymentEvent field.
func (r *queryResolver) PaymentEvent(ctx context.Context, tenantID string, idempotencyKey string) (*model.PaymentEvent, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.PaymentEvent")
	defer span.End()
	r.Metrics.QueryTotal.Add(ctx, 1, withAttr("operation", "PaymentEvent"))

	resp, err := r.Clients.Ingestion.GetPaymentStatus(ctx, tenantID, idempotencyKey)
	if err != nil {
		return nil, err
	}
	// GetPaymentStatus only returns status/reason; return a minimal object
	return &model.PaymentEvent{
		TenantID:       tenantID,
		IdempotencyKey: idempotencyKey,
		Status:         mapPaymentStatus(resp.Status),
		// Other fields are not returned by GetPaymentStatus
	}, nil
}

// Decision is the resolver for the decision field.
func (r *queryResolver) Decision(ctx context.Context, tenantID string, paymentEventID string) (*model.Decision, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.Decision")
	defer span.End()
	r.Metrics.QueryTotal.Add(ctx, 1, withAttr("operation", "Decision"))

	type cacheKey struct {
		TenantID       string
		PaymentEventID string
	}
	var cached model.Decision
	if hit, _ := r.Cache.Get(ctx, tenantID, "Decision", cacheKey{tenantID, paymentEventID}, &cached); hit {
		r.Metrics.CacheHits.Add(ctx, 1)
		return &cached, nil
	}
	r.Metrics.CacheMisses.Add(ctx, 1)

	d, err := r.Clients.Decision.GetDecision(ctx, tenantID, paymentEventID)
	if err != nil {
		return nil, err
	}
	result := protoToDecision(d)
	r.Cache.Set(ctx, tenantID, "Decision", cacheKey{tenantID, paymentEventID}, result)
	return result, nil
}

// Decisions is the resolver for the decisions field.
func (r *queryResolver) Decisions(ctx context.Context, tenantID string, page *int, pageSize *int, outcomeFilter *string) (*model.DecisionConnection, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.Decisions")
	defer span.End()
	r.Metrics.QueryTotal.Add(ctx, 1, withAttr("operation", "Decisions"))

	p := int32(derefInt(page, 1))
	ps := int32(derefInt(pageSize, 20))
	of := derefStr(outcomeFilter, "")

	decisions, total, err := r.Clients.Decision.ListDecisions(ctx, tenantID, p, ps, of)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Decision, len(decisions))
	for i, d := range decisions {
		out[i] = protoToDecision(d)
	}
	return &model.DecisionConnection{Decisions: out, Total: int(total)}, nil
}

// Explanation is the resolver for the explanation field.
func (r *queryResolver) Explanation(ctx context.Context, tenantID string, paymentEventID string) (*model.Explanation, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.Explanation")
	defer span.End()
	r.Metrics.QueryTotal.Add(ctx, 1, withAttr("operation", "Explanation"))

	expl, err := r.Clients.Explanation.GetExplanation(ctx, tenantID, paymentEventID)
	if err != nil {
		return nil, err
	}

	contributions := make([]*model.RuleContribution, len(expl.RuleContributions))
	for i, rc := range expl.RuleContributions {
		contributions[i] = &model.RuleContribution{
			RuleID:   rc.RuleId,
			RuleName: rc.RuleName,
			Matched:  rc.Matched,
			Action:   rc.Action,
			Reason:   rc.Reason,
		}
	}
	featureValues := make([]*model.FeatureValue, len(expl.FeatureValues))
	for i, fv := range expl.FeatureValues {
		featureValues[i] = &model.FeatureValue{Name: fv.Name, Value: fv.Value}
	}

	return &model.Explanation{
		ID:                expl.Id,
		DecisionID:        expl.DecisionId,
		TenantID:          expl.TenantId,
		PaymentEventID:    expl.PaymentEventId,
		Outcome:           mapOutcome(decisionpb.Outcome(expl.Outcome)),
		ConfidenceScore:   expl.ConfidenceScore,
		RuleContributions: contributions,
		FeatureValues:     featureValues,
		Narrative:         expl.Narrative,
		PolicyVersion:     expl.PolicyVersion,
		GeneratedAt:       tsToTime(expl.GeneratedAt),
	}, nil
}

// Case is the resolver for the case field.
func (r *queryResolver) Case(ctx context.Context, caseID string) (*model.Case, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.Case")
	defer span.End()
	r.Metrics.QueryTotal.Add(ctx, 1, withAttr("operation", "Case"))

	c, err := r.Clients.CaseMgmt.GetCase(ctx, caseID)
	if err != nil {
		return nil, err
	}
	return protoToCase(c), nil
}

// Cases is the resolver for the cases field.
func (r *queryResolver) Cases(ctx context.Context, tenantID string, status *model.CaseStatus, assigneeID *string, pageSize *int, pageToken *string) (*model.CaseConnection, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.Cases")
	defer span.End()
	r.Metrics.QueryTotal.Add(ctx, 1, withAttr("operation", "Cases"))

	req := &casemanagementpb.ListCasesRequest{
		TenantId:  tenantID,
		PageSize:  int32(derefInt(pageSize, 20)),
		PageToken: derefStr(pageToken, ""),
	}
	if status != nil {
		req.Status = mapCaseStatusToProto(*status)
	}
	if assigneeID != nil {
		req.AssigneeId = *assigneeID
	}

	cases, nextToken, err := r.Clients.CaseMgmt.ListCases(ctx, req)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Case, len(cases))
	for i, c := range cases {
		out[i] = protoToCase(c)
	}
	return &model.CaseConnection{Cases: out, NextPageToken: nextToken}, nil
}

// Rules is the resolver for the rules field.
func (r *queryResolver) Rules(ctx context.Context, tenantID string, includeDisabled *bool) ([]*model.Rule, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.Rules")
	defer span.End()
	r.Metrics.QueryTotal.Add(ctx, 1, withAttr("operation", "Rules"))

	incl := false
	if includeDisabled != nil {
		incl = *includeDisabled
	}

	var cached []*model.Rule
	if hit, _ := r.Cache.Get(ctx, tenantID, "Rules", map[string]any{"incl": incl}, &cached); hit {
		r.Metrics.CacheHits.Add(ctx, 1)
		return cached, nil
	}
	r.Metrics.CacheMisses.Add(ctx, 1)

	rules, err := r.Clients.Rules.ListRules(ctx, tenantID, incl)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Rule, len(rules))
	for i, rule := range rules {
		out[i] = protoToRule(rule)
	}
	r.Cache.Set(ctx, tenantID, "Rules", map[string]any{"incl": incl}, out)
	return out, nil
}

// WorkflowTemplate is the resolver for the workflowTemplate field.
func (r *queryResolver) WorkflowTemplate(ctx context.Context, templateID string, tenantID string) (*model.WorkflowTemplate, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.WorkflowTemplate")
	defer span.End()
	r.Metrics.QueryTotal.Add(ctx, 1, withAttr("operation", "WorkflowTemplate"))

	tmpl, err := r.Clients.Workflow.GetTemplate(ctx, templateID, tenantID)
	if err != nil {
		return nil, err
	}
	return protoToWorkflowTemplate(tmpl), nil
}

// WorkflowTemplates is the resolver for the workflowTemplates field.
func (r *queryResolver) WorkflowTemplates(ctx context.Context, tenantID string) ([]*model.WorkflowTemplate, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.WorkflowTemplates")
	defer span.End()
	r.Metrics.QueryTotal.Add(ctx, 1, withAttr("operation", "WorkflowTemplates"))

	// WorkflowService doesn't have a ListTemplates RPC in the proto — fetch by name placeholder
	// Fall back to the get-by-tenant approach via ListTransitions with a dummy call
	// NOTE: The proto doesn't have ListTemplates. Return empty until extended.
	return []*model.WorkflowTemplate{}, nil
}

// TenantConfig is the resolver for the tenantConfig field.
func (r *queryResolver) TenantConfig(ctx context.Context, tenantID string) (*model.Tenant, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.TenantConfig")
	defer span.End()
	r.Metrics.QueryTotal.Add(ctx, 1, withAttr("operation", "TenantConfig"))

	var cached model.Tenant
	if hit, _ := r.Cache.Get(ctx, tenantID, "TenantConfig", tenantID, &cached); hit {
		r.Metrics.CacheHits.Add(ctx, 1)
		return &cached, nil
	}
	r.Metrics.CacheMisses.Add(ctx, 1)

	t, err := r.Clients.Tenant.GetTenantConfig(ctx, tenantID)
	if err != nil {
		return nil, err
	}
	result := protoToTenant(t)
	r.Cache.Set(ctx, tenantID, "TenantConfig", tenantID, result)
	return result, nil
}

// FeatureFlags is the resolver for the featureFlags field.
func (r *queryResolver) FeatureFlags(ctx context.Context, tenantID string) ([]*model.FeatureFlag, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.FeatureFlags")
	defer span.End()
	r.Metrics.QueryTotal.Add(ctx, 1, withAttr("operation", "FeatureFlags"))

	flags, err := r.Clients.Tenant.GetFeatureFlags(ctx, tenantID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.FeatureFlag, len(flags))
	for i, f := range flags {
		out[i] = &model.FeatureFlag{
			Key:               f.Key,
			Enabled:           f.Enabled,
			RolloutPercentage: int(f.RolloutPercentage),
		}
	}
	return out, nil
}

// AuditTrail is the resolver for the auditTrail field.
func (r *queryResolver) AuditTrail(ctx context.Context, query model.AuditQueryInput) (*model.AuditConnection, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.AuditTrail")
	defer span.End()
	r.Metrics.QueryTotal.Add(ctx, 1, withAttr("operation", "AuditTrail"))

	aq := &audittrailpb.AuditQuery{
		TenantId:  query.TenantID,
		PageSize:  int32(derefInt(query.PageSize, 50)),
		PageToken: derefStr(query.PageToken, ""),
	}
	if query.ActorID != nil {
		aq.ActorId = *query.ActorID
	}
	if query.ResourceType != nil {
		aq.ResourceType = *query.ResourceType
	}
	if query.ResourceID != nil {
		aq.ResourceId = *query.ResourceID
	}
	if query.Action != nil {
		aq.Action = *query.Action
	}
	if query.FromTime != nil {
		aq.FromTime = timestamppb.New(*query.FromTime)
	}
	if query.ToTime != nil {
		aq.ToTime = timestamppb.New(*query.ToTime)
	}

	events, nextToken, err := r.Clients.Audit.QueryTrail(ctx, &audittrailpb.QueryAuditTrailRequest{Query: aq})
	if err != nil {
		return nil, err
	}
	out := make([]*model.AuditEvent, len(events))
	for i, e := range events {
		out[i] = protoToAuditEvent(e)
	}
	return &model.AuditConnection{Events: out, NextPageToken: nextToken}, nil
}

// VerifyChainIntegrity is the resolver for the verifyChainIntegrity field.
func (r *queryResolver) VerifyChainIntegrity(ctx context.Context, tenantID string, limit *int) (*model.ChainVerification, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.VerifyChainIntegrity")
	defer span.End()

	lim := int32(derefInt(limit, 1000))
	valid, checked, brokenAt, err := r.Clients.Audit.VerifyChain(ctx, tenantID, lim)
	if err != nil {
		return nil, err
	}
	return &model.ChainVerification{
		Valid:         valid,
		EventsChecked: int(checked),
		BrokenAtID:    brokenAt,
	}, nil
}

// NotificationStatus is the resolver for the notificationStatus field.
func (r *queryResolver) NotificationStatus(ctx context.Context, notificationID string, tenantID string) (*model.Notification, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.NotificationStatus")
	defer span.End()

	n, err := r.Clients.Notification.GetDeliveryStatus(ctx, notificationID, tenantID)
	if err != nil {
		return nil, err
	}
	return protoToNotification(n), nil
}

// QueryLogs is the resolver for the queryLogs field.
func (r *queryResolver) QueryLogs(ctx context.Context, query model.LogQueryInput) (*model.LogConnection, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.QueryLogs")
	defer span.End()
	r.Metrics.QueryTotal.Add(ctx, 1, withAttr("operation", "QueryLogs"))

	req := &opsquerypb.LogQuery{
		Service:        derefStr(query.Service, ""),
		Severity:       derefStr(query.Severity, ""),
		TraceId:        derefStr(query.TraceID, ""),
		TenantId:       derefStr(query.TenantID, ""),
		MessageContains: derefStr(query.MessageContains, ""),
		PageSize:       int32(derefInt(query.PageSize, 50)),
		PageToken:      derefStr(query.PageToken, ""),
	}
	if query.FromTime != nil {
		req.FromTime = timestamppb.New(*query.FromTime)
	}
	if query.ToTime != nil {
		req.ToTime = timestamppb.New(*query.ToTime)
	}

	entries, nextToken, err := r.Clients.OpsQuery.QueryLogs(ctx, &opsquerypb.QueryLogsRequest{Query: req})
	if err != nil {
		return nil, err
	}
	out := make([]*model.LogEntry, len(entries))
	for i, e := range entries {
		out[i] = &model.LogEntry{
			ID:          e.Id,
			Service:     e.Service,
			Severity:    e.Severity,
			Message:     e.Message,
			TraceID:     e.TraceId,
			SpanID:      e.SpanId,
			TenantID:    e.TenantId,
			Environment: e.Environment,
			Timestamp:   tsToTime(e.Timestamp),
		}
	}
	return &model.LogConnection{Entries: out, NextPageToken: nextToken}, nil
}

// QueryTraces is the resolver for the queryTraces field.
func (r *queryResolver) QueryTraces(ctx context.Context, traceID *string, service *string, fromTime *time.Time, toTime *time.Time, limit *int) ([]*model.TraceSpan, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.QueryTraces")
	defer span.End()
	r.Metrics.QueryTotal.Add(ctx, 1, withAttr("operation", "QueryTraces"))

	spans, err := r.Clients.OpsQuery.QueryTraces(ctx,
		derefStr(traceID, ""),
		derefStr(service, ""),
		fromTime, toTime,
		int32(derefInt(limit, 50)),
	)
	if err != nil {
		return nil, err
	}
	out := make([]*model.TraceSpan, len(spans))
	for i, s := range spans {
		out[i] = &model.TraceSpan{
			TraceID:      s.TraceId,
			SpanID:       s.SpanId,
			ParentSpanID: s.ParentSpanId,
			Service:      s.Service,
			Operation:    s.Operation,
			DurationMs:   int(s.DurationMs),
			Status:       s.Status,
			StartTime:    tsToTime(s.StartTime),
		}
	}
	return out, nil
}

// SloStatus is the resolver for the sloStatus field.
func (r *queryResolver) SloStatus(ctx context.Context, service string, window string) (*model.SLOStatus, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.SloStatus")
	defer span.End()

	status, err := r.Clients.OpsQuery.GetSLOStatus(ctx, service, window)
	if err != nil {
		return nil, err
	}
	return &model.SLOStatus{
		Service:      status.Service,
		ErrorRate:    status.ErrorRate,
		P50LatencyMs: status.P50LatencyMs,
		P95LatencyMs: status.P95LatencyMs,
		P99LatencyMs: status.P99LatencyMs,
		Availability: status.Availability,
		Window:       status.Window,
	}, nil
}

// Alerts is the resolver for the alerts field.
func (r *queryResolver) Alerts(ctx context.Context, service *string, severity *string, activeOnly *bool, limit *int) ([]*model.Alert, error) {
	ctx, span := otel.Tracer("graphql-bff").Start(ctx, "query.Alerts")
	defer span.End()

	ao := false
	if activeOnly != nil {
		ao = *activeOnly
	}

	alerts, err := r.Clients.OpsQuery.ListAlerts(ctx,
		derefStr(service, ""),
		derefStr(severity, ""),
		ao,
		int32(derefInt(limit, 50)),
	)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Alert, len(alerts))
	for i, a := range alerts {
		out[i] = &model.Alert{
			Name:     a.Name,
			Service:  a.Service,
			Severity: a.Severity,
			State:    a.State,
			Summary:  a.Summary,
			FiredAt:  tsToTime(a.FiredAt),
		}
	}
	return out, nil
}

// ── Root resolver type implementations ────────────────────────────────────────

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// ══════════════════════════════════════════════════════════════════════════════
// PROTO → MODEL CONVERSION HELPERS
// ══════════════════════════════════════════════════════════════════════════════

func protoToDecision(d *decisionpb.Decision) *model.Decision {
	if d == nil {
		return nil
	}
	return &model.Decision{
		ID:              d.Id,
		PaymentEventID:  d.PaymentEventId,
		TenantID:        d.TenantId,
		Outcome:         mapOutcome(d.Outcome),
		ReasonCodes:     d.ReasonCodes,
		ConfidenceScore: d.ConfidenceScore,
		Overridden:      d.Overridden,
		LatencyMs:       int(d.LatencyMs),
		CreatedAt:       tsToTime(d.CreatedAt),
	}
}

func protoToCase(c *casemanagementpb.Case) *model.Case {
	if c == nil {
		return nil
	}
	return &model.Case{
		ID:             c.Id,
		DecisionID:     c.DecisionId,
		TenantID:       c.TenantId,
		AssigneeID:     c.AssigneeId,
		Status:         mapCaseStatus(c.Status),
		Priority:       mapCasePriority(c.Priority),
		PaymentEventID: c.PaymentEventId,
		Outcome:        c.Outcome,
		SLADeadline:    tsToTime(c.SlaDeadline),
		CreatedAt:      tsToTime(c.CreatedAt),
		UpdatedAt:      tsToTime(c.UpdatedAt),
	}
}

func protoToWorkflowTemplate(tmpl *workflowpb.WorkflowTemplate) *model.WorkflowTemplate {
	if tmpl == nil {
		return nil
	}
	transitions := make([]*model.WorkflowTransition, len(tmpl.Transitions))
	for i, t := range tmpl.Transitions {
		guards := make([]*model.WorkflowGuard, len(t.Guards))
		for j, g := range t.Guards {
			guards[j] = &model.WorkflowGuard{
				Type:      mapGuardType(g.Type),
				Role:      g.Role,
				Condition: g.Condition,
			}
		}
		transitions[i] = &model.WorkflowTransition{
			FromState:    t.FromState,
			ToState:      t.ToState,
			RequiredRole: t.RequiredRole,
			Guards:       guards,
		}
	}
	return &model.WorkflowTemplate{
		ID:          tmpl.Id,
		TenantID:    tmpl.TenantId,
		Name:        tmpl.Name,
		Version:     int(tmpl.Version),
		States:      tmpl.States,
		Transitions: transitions,
		CreatedAt:   tsToTime(tmpl.CreatedAt),
		UpdatedAt:   tsToTime(tmpl.UpdatedAt),
	}
}

func protoToRule(r *rulesengine.Rule) *model.Rule {
	if r == nil {
		return nil
	}
	return &model.Rule{
		ID:        r.Id,
		TenantID:  r.TenantId,
		Name:      r.Name,
		Version:   int(r.Version),
		Action:    mapRuleAction(r.Action),
		Priority:  int(r.Priority),
		Enabled:   r.Enabled,
		CreatedAt: tsToTime(r.CreatedAt),
		UpdatedAt: tsToTime(r.UpdatedAt),
	}
}

func protoToTenant(t *tenantpb.Tenant) *model.Tenant {
	if t == nil {
		return nil
	}
	cfg := &model.TenantConfig{}
	if t.Config != nil {
		flags := make([]*model.FeatureFlag, len(t.Config.FeatureFlags))
		for i, f := range t.Config.FeatureFlags {
			flags[i] = &model.FeatureFlag{
				Key:               f.Key,
				Enabled:           f.Enabled,
				RolloutPercentage: int(f.RolloutPercentage),
			}
		}
		cfg = &model.TenantConfig{
			RuleSetID:          t.Config.RuleSetId,
			WorkflowTemplateID: t.Config.WorkflowTemplateId,
			FeatureFlags:       flags,
			Version:            int(t.Config.Version),
		}
	}
	return &model.Tenant{
		ID:        t.Id,
		Name:      t.Name,
		Status:    mapTenantStatus(t.Status),
		CreatedAt: tsToTime(t.CreatedAt),
		Config:    cfg,
	}
}

func protoToAuditEvent(e *audittrailpb.AuditEvent) *model.AuditEvent {
	if e == nil {
		return nil
	}
	return &model.AuditEvent{
		ID:           e.Id,
		TenantID:     e.TenantId,
		ActorID:      e.ActorId,
		Action:       e.Action,
		ResourceType: e.ResourceType,
		ResourceID:   e.ResourceId,
		SourceTopic:  e.SourceTopic,
		Hash:         e.Hash,
		PreviousHash: e.PreviousHash,
		OccurredAt:   tsToTime(e.OccurredAt),
	}
}

func protoToNotification(n *notificationpb.Notification) *model.Notification {
	if n == nil {
		return nil
	}
	return &model.Notification{
		ID:        n.Id,
		TenantID:  n.TenantId,
		Type:      n.Type,
		Recipient: n.Recipient,
		Channel:   mapNotificationChannel(n.Channel),
		Status:    mapNotificationStatus(n.Status),
		Attempts:  int(n.Attempts),
		CreatedAt: tsToTime(n.CreatedAt),
	}
}

func protoToNotificationPreference(p *notificationpb.NotificationPreference) *model.NotificationPreference {
	if p == nil {
		return nil
	}
	return &model.NotificationPreference{
		TenantID:  p.TenantId,
		Channel:   mapNotificationChannel(p.Channel),
		EventType: p.EventType,
		Enabled:   p.Enabled,
		Config:    p.Config,
	}
}

// ══════════════════════════════════════════════════════════════════════════════
// ENUM MAPPERS
// ══════════════════════════════════════════════════════════════════════════════

func mapOutcome(o decisionpb.Outcome) model.Outcome {
	switch o {
	case decisionpb.Outcome_OUTCOME_APPROVE:
		return model.OutcomeApprove
	case decisionpb.Outcome_OUTCOME_FLAG:
		return model.OutcomeFlag
	case decisionpb.Outcome_OUTCOME_REVIEW:
		return model.OutcomeReview
	case decisionpb.Outcome_OUTCOME_BLOCK:
		return model.OutcomeBlock
	default:
		return model.OutcomeApprove
	}
}

func mapOutcomeToProto(o model.Outcome) decisionpb.Outcome {
	switch o {
	case model.OutcomeApprove:
		return decisionpb.Outcome_OUTCOME_APPROVE
	case model.OutcomeFlag:
		return decisionpb.Outcome_OUTCOME_FLAG
	case model.OutcomeReview:
		return decisionpb.Outcome_OUTCOME_REVIEW
	case model.OutcomeBlock:
		return decisionpb.Outcome_OUTCOME_BLOCK
	default:
		return decisionpb.Outcome_OUTCOME_UNSPECIFIED
	}
}

func mapPaymentStatus(s ingestion.PaymentStatus) model.PaymentStatus {
	switch s {
	case ingestion.PaymentStatus_PAYMENT_STATUS_RECEIVED:
		return model.PaymentStatusReceived
	case ingestion.PaymentStatus_PAYMENT_STATUS_DUPLICATE:
		return model.PaymentStatusDuplicate
	case ingestion.PaymentStatus_PAYMENT_STATUS_REJECTED:
		return model.PaymentStatusRejected
	default:
		return model.PaymentStatusReceived
	}
}

func mapCaseStatus(s casemanagementpb.CaseStatus) model.CaseStatus {
	switch s {
	case casemanagementpb.CaseStatus_CASE_STATUS_OPEN:
		return model.CaseStatusOpen
	case casemanagementpb.CaseStatus_CASE_STATUS_IN_REVIEW:
		return model.CaseStatusInReview
	case casemanagementpb.CaseStatus_CASE_STATUS_RESOLVED:
		return model.CaseStatusResolved
	case casemanagementpb.CaseStatus_CASE_STATUS_ESCALATED:
		return model.CaseStatusEscalated
	default:
		return model.CaseStatusOpen
	}
}

func mapCaseStatusToProto(s model.CaseStatus) casemanagementpb.CaseStatus {
	switch s {
	case model.CaseStatusOpen:
		return casemanagementpb.CaseStatus_CASE_STATUS_OPEN
	case model.CaseStatusInReview:
		return casemanagementpb.CaseStatus_CASE_STATUS_IN_REVIEW
	case model.CaseStatusResolved:
		return casemanagementpb.CaseStatus_CASE_STATUS_RESOLVED
	case model.CaseStatusEscalated:
		return casemanagementpb.CaseStatus_CASE_STATUS_ESCALATED
	default:
		return casemanagementpb.CaseStatus_CASE_STATUS_UNSPECIFIED
	}
}

func mapCasePriority(p casemanagementpb.CasePriority) model.CasePriority {
	switch p {
	case casemanagementpb.CasePriority_CASE_PRIORITY_LOW:
		return model.CasePriorityLow
	case casemanagementpb.CasePriority_CASE_PRIORITY_MEDIUM:
		return model.CasePriorityMedium
	case casemanagementpb.CasePriority_CASE_PRIORITY_HIGH:
		return model.CasePriorityHigh
	case casemanagementpb.CasePriority_CASE_PRIORITY_CRITICAL:
		return model.CasePriorityCritical
	default:
		return model.CasePriorityLow
	}
}

func mapCasePriorityToProto(p model.CasePriority) casemanagementpb.CasePriority {
	switch p {
	case model.CasePriorityLow:
		return casemanagementpb.CasePriority_CASE_PRIORITY_LOW
	case model.CasePriorityMedium:
		return casemanagementpb.CasePriority_CASE_PRIORITY_MEDIUM
	case model.CasePriorityHigh:
		return casemanagementpb.CasePriority_CASE_PRIORITY_HIGH
	case model.CasePriorityCritical:
		return casemanagementpb.CasePriority_CASE_PRIORITY_CRITICAL
	default:
		return casemanagementpb.CasePriority_CASE_PRIORITY_UNSPECIFIED
	}
}

func mapRuleAction(a rulesengine.RuleAction) model.RuleAction {
	switch a {
	case rulesengine.RuleAction_RULE_ACTION_APPROVE:
		return model.RuleActionApprove
	case rulesengine.RuleAction_RULE_ACTION_FLAG:
		return model.RuleActionFlag
	case rulesengine.RuleAction_RULE_ACTION_REVIEW:
		return model.RuleActionReview
	case rulesengine.RuleAction_RULE_ACTION_BLOCK:
		return model.RuleActionBlock
	default:
		return model.RuleActionApprove
	}
}

func mapRuleActionToProto(a model.RuleAction) rulesengine.RuleAction {
	switch a {
	case model.RuleActionApprove:
		return rulesengine.RuleAction_RULE_ACTION_APPROVE
	case model.RuleActionFlag:
		return rulesengine.RuleAction_RULE_ACTION_FLAG
	case model.RuleActionReview:
		return rulesengine.RuleAction_RULE_ACTION_REVIEW
	case model.RuleActionBlock:
		return rulesengine.RuleAction_RULE_ACTION_BLOCK
	default:
		return rulesengine.RuleAction_RULE_ACTION_UNSPECIFIED
	}
}

func mapTenantStatus(s tenantpb.TenantStatus) model.TenantStatus {
	switch s {
	case tenantpb.TenantStatus_TENANT_STATUS_ACTIVE:
		return model.TenantStatusActive
	case tenantpb.TenantStatus_TENANT_STATUS_INACTIVE:
		return model.TenantStatusInactive
	case tenantpb.TenantStatus_TENANT_STATUS_ONBOARDING:
		return model.TenantStatusOnboarding
	default:
		return model.TenantStatusActive
	}
}

func mapNotificationChannel(c notificationpb.NotificationChannel) model.NotificationChannel {
	switch c {
	case notificationpb.NotificationChannel_NOTIFICATION_CHANNEL_EMAIL:
		return model.NotificationChannelEmail
	case notificationpb.NotificationChannel_NOTIFICATION_CHANNEL_WEBHOOK:
		return model.NotificationChannelWebhook
	case notificationpb.NotificationChannel_NOTIFICATION_CHANNEL_SLACK:
		return model.NotificationChannelSLACk
	default:
		return model.NotificationChannelWebhook
	}
}

func mapNotificationChannelToProto(c model.NotificationChannel) notificationpb.NotificationChannel {
	switch c {
	case model.NotificationChannelEmail:
		return notificationpb.NotificationChannel_NOTIFICATION_CHANNEL_EMAIL
	case model.NotificationChannelWebhook:
		return notificationpb.NotificationChannel_NOTIFICATION_CHANNEL_WEBHOOK
	case model.NotificationChannelSLACk:
		return notificationpb.NotificationChannel_NOTIFICATION_CHANNEL_SLACK
	default:
		return notificationpb.NotificationChannel_NOTIFICATION_CHANNEL_UNSPECIFIED
	}
}

func mapNotificationStatus(s notificationpb.NotificationStatus) model.NotificationStatus {
	switch s {
	case notificationpb.NotificationStatus_NOTIFICATION_STATUS_PENDING:
		return model.NotificationStatusPending
	case notificationpb.NotificationStatus_NOTIFICATION_STATUS_DELIVERED:
		return model.NotificationStatusDelivered
	case notificationpb.NotificationStatus_NOTIFICATION_STATUS_FAILED:
		return model.NotificationStatusFailed
	case notificationpb.NotificationStatus_NOTIFICATION_STATUS_RETRYING:
		return model.NotificationStatusRetrying
	default:
		return model.NotificationStatusPending
	}
}

func mapGuardType(t workflowpb.GuardType) model.GuardType {
	switch t {
	case workflowpb.GuardType_GUARD_TYPE_ROLE_REQUIRED:
		return model.GuardTypeRoleRequired
	case workflowpb.GuardType_GUARD_TYPE_CONDITION:
		return model.GuardTypeCondition
	default:
		return model.GuardTypeRoleRequired
	}
}

// ══════════════════════════════════════════════════════════════════════════════
// UTILITY HELPERS
// ══════════════════════════════════════════════════════════════════════════════

func tsToTime(ts interface{ AsTime() time.Time }) time.Time {
	if ts == nil {
		return time.Time{}
	}
	return ts.AsTime()
}

func derefStr(s *string, fallback string) string {
	if s != nil {
		return *s
	}
	return fallback
}

func derefInt(i *int, fallback int) int {
	if i != nil {
		return *i
	}
	return fallback
}

func withAttr(key, value string) otelmetric.AddOption {
	return otelmetric.WithAttributes(attribute.String(key, value))
}



