apiVersion: v1
kind: Service
metadata:
  name: case-management
  namespace: risk-platform
spec:
  selector:
    app: case-management
  ports:
    - name: grpc
      port: 50057
      targetPort: 50057
    - name: metrics
      port: 9097
      targetPort: 9097
  type: ClusterIP
