apiVersion: v1
kind: Service
metadata:
  name: log-ingestion
  namespace: risk-platform
spec:
  selector:
    app: log-ingestion
  ports:
    - name: grpc
      port: 50062
      targetPort: 50062
    - name: metrics
      port: 9102
      targetPort: 9102
  type: ClusterIP
