apiVersion: v1
kind: Service
metadata:
  name: decision
  namespace: risk-platform
spec:
  selector:
    app: decision
  ports:
    - name: grpc
      port: 50056
      targetPort: 50056
    - name: metrics
      port: 9096
      targetPort: 9096
  type: ClusterIP
