apiVersion: v1
kind: Service
metadata:
  name: audit-trail
  namespace: risk-platform
spec:
  selector:
    app: audit-trail
  ports:
    - name: grpc
      port: 50059
      targetPort: 50059
    - name: metrics
      port: 9099
      targetPort: 9099
  type: ClusterIP
