// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Alert struct {
	Name     string    `json:"name"`
	Service  string    `json:"service"`
	Severity string    `json:"severity"`
	State    string    `json:"state"`
	Summary  string    `json:"summary"`
	FiredAt  time.Time `json:"firedAt"`
}

type AssignCaseInput struct {
	CaseID     string `json:"caseId"`
	AssigneeID string `json:"assigneeId"`
	ActorID    string `json:"actorId"`
}

type AuditConnection struct {
	Events        []*AuditEvent `json:"events"`
	NextPageToken string        `json:"nextPageToken"`
}

type AuditEvent struct {
	ID           string    `json:"id"`
	TenantID     string    `json:"tenantId"`
	ActorID      string    `json:"actorId"`
	Action       string    `json:"action"`
	ResourceType string    `json:"resourceType"`
	ResourceID   string    `json:"resourceId"`
	SourceTopic  string    `json:"sourceTopic"`
	Hash         string    `json:"hash"`
	PreviousHash string    `json:"previousHash"`
	OccurredAt   time.Time `json:"occurredAt"`
}

type AuditQueryInput struct {
	TenantID     string     `json:"tenantId"`
	ActorID      *string    `json:"actorId,omitempty"`
	ResourceType *string    `json:"resourceType,omitempty"`
	ResourceID   *string    `json:"resourceId,omitempty"`
	Action       *string    `json:"action,omitempty"`
	FromTime     *time.Time `json:"fromTime,omitempty"`
	ToTime       *time.Time `json:"toTime,omitempty"`
	PageSize     *int       `json:"pageSize,omitempty"`
	PageToken    *string    `json:"pageToken,omitempty"`
}

type Case struct {
	ID             string       `json:"id"`
	DecisionID     string       `json:"decisionId"`
	TenantID       string       `json:"tenantId"`
	AssigneeID     string       `json:"assigneeId"`
	Status         CaseStatus   `json:"status"`
	Priority       CasePriority `json:"priority"`
	PaymentEventID string       `json:"paymentEventId"`
	Outcome        string       `json:"outcome"`
	SLADeadline    time.Time    `json:"slaDeadline"`
	CreatedAt      time.Time    `json:"createdAt"`
	UpdatedAt      time.Time    `json:"updatedAt"`
}

type CaseConnection struct {
	Cases         []*Case `json:"cases"`
	NextPageToken string  `json:"nextPageToken"`
}

type ChainVerification struct {
	Valid         bool   `json:"valid"`
	EventsChecked int    `json:"eventsChecked"`
	BrokenAtID    string `json:"brokenAtId"`
}

type CreateCaseInput struct {
	DecisionID     string       `json:"decisionId"`
	TenantID       string       `json:"tenantId"`
	PaymentEventID string       `json:"paymentEventId"`
	Outcome        string       `json:"outcome"`
	Priority       CasePriority `json:"priority"`
}

type CreateRuleInput struct {
	TenantID   string     `json:"tenantId"`
	Name       string     `json:"name"`
	Expression string     `json:"expression"`
	Action     RuleAction `json:"action"`
	Priority   int        `json:"priority"`
}

type CreateTenantInput struct {
	Name               string `json:"name"`
	RuleSetID          string `json:"ruleSetId"`
	WorkflowTemplateID string `json:"workflowTemplateId"`
}

type CreateWorkflowTemplateInput struct {
	TenantID    string             `json:"tenantId"`
	Name        string             `json:"name"`
	States      []string           `json:"states"`
	Transitions []*TransitionInput `json:"transitions"`
}

type Decision struct {
	ID              string    `json:"id"`
	PaymentEventID  string    `json:"paymentEventId"`
	TenantID        string    `json:"tenantId"`
	Outcome         Outcome   `json:"outcome"`
	ReasonCodes     []string  `json:"reasonCodes"`
	ConfidenceScore float64   `json:"confidenceScore"`
	Overridden      bool      `json:"overridden"`
	LatencyMs       int       `json:"latencyMs"`
	CreatedAt       time.Time `json:"createdAt"`
}

type DecisionConnection struct {
	Decisions []*Decision `json:"decisions"`
	Total     int         `json:"total"`
}

type DecisionOverride struct {
	ID              string    `json:"id"`
	DecisionID      string    `json:"decisionId"`
	AnalystID       string    `json:"analystId"`
	PreviousOutcome Outcome   `json:"previousOutcome"`
	NewOutcome      Outcome   `json:"newOutcome"`
	Reason          string    `json:"reason"`
	CreatedAt       time.Time `json:"createdAt"`
}

type DeleteRuleInput struct {
	RuleID   string `json:"ruleId"`
	TenantID string `json:"tenantId"`
}

type EscalateCaseInput struct {
	CaseID  string `json:"caseId"`
	ActorID string `json:"actorId"`
	Reason  string `json:"reason"`
}

type EvaluateTransitionInput struct {
	TemplateID string `json:"templateId"`
	TenantID   string `json:"tenantId"`
	FromState  string `json:"fromState"`
	ToState    string `json:"toState"`
	ActorRole  string `json:"actorRole"`
}

type Explanation struct {
	ID                string              `json:"id"`
	DecisionID        string              `json:"decisionId"`
	TenantID          string              `json:"tenantId"`
	PaymentEventID    string              `json:"paymentEventId"`
	Outcome           Outcome             `json:"outcome"`
	ConfidenceScore   float64             `json:"confidenceScore"`
	RuleContributions []*RuleContribution `json:"ruleContributions"`
	FeatureValues     []*FeatureValue     `json:"featureValues"`
	Narrative         string              `json:"narrative"`
	PolicyVersion     string              `json:"policyVersion"`
	GeneratedAt       time.Time           `json:"generatedAt"`
}

type FeatureFlag struct {
	Key               string `json:"key"`
	Enabled           bool   `json:"enabled"`
	RolloutPercentage int    `json:"rolloutPercentage"`
}

type FeatureValue struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type IngestPaymentInput struct {
	IdempotencyKey string `json:"idempotencyKey"`
	TenantID       string `json:"tenantId"`
	Amount         int    `json:"amount"`
	Currency       string `json:"currency"`
	Source         string `json:"source"`
	Destination    string `json:"destination"`
}

type IngestionResult struct {
	EventID string        `json:"eventId"`
	Status  PaymentStatus `json:"status"`
	Reason  string        `json:"reason"`
}

type LogConnection struct {
	Entries       []*LogEntry `json:"entries"`
	NextPageToken string      `json:"nextPageToken"`
}

type LogEntry struct {
	ID          string    `json:"id"`
	Service     string    `json:"service"`
	Severity    string    `json:"severity"`
	Message     string    `json:"message"`
	TraceID     string    `json:"traceId"`
	SpanID      string    `json:"spanId"`
	TenantID    string    `json:"tenantId"`
	Environment string    `json:"environment"`
	Timestamp   time.Time `json:"timestamp"`
}

type LogQueryInput struct {
	Service         *string    `json:"service,omitempty"`
	Severity        *string    `json:"severity,omitempty"`
	TraceID         *string    `json:"traceId,omitempty"`
	TenantID        *string    `json:"tenantId,omitempty"`
	MessageContains *string    `json:"messageContains,omitempty"`
	FromTime        *time.Time `json:"fromTime,omitempty"`
	ToTime          *time.Time `json:"toTime,omitempty"`
	PageSize        *int       `json:"pageSize,omitempty"`
	PageToken       *string    `json:"pageToken,omitempty"`
}

type Mutation struct {
}

type Notification struct {
	ID        string              `json:"id"`
	TenantID  string              `json:"tenantId"`
	Type      string              `json:"type"`
	Recipient string              `json:"recipient"`
	Channel   NotificationChannel `json:"channel"`
	Status    NotificationStatus  `json:"status"`
	Attempts  int                 `json:"attempts"`
	CreatedAt time.Time           `json:"createdAt"`
}

type NotificationPreference struct {
	TenantID  string              `json:"tenantId"`
	Channel   NotificationChannel `json:"channel"`
	EventType string              `json:"eventType"`
	Enabled   bool                `json:"enabled"`
	Config    string              `json:"config"`
}

type NotificationSendResult struct {
	NotificationID string             `json:"notificationId"`
	Status         NotificationStatus `json:"status"`
}

type OverrideDecisionInput struct {
	DecisionID string  `json:"decisionId"`
	AnalystID  string  `json:"analystId"`
	NewOutcome Outcome `json:"newOutcome"`
	Reason     string  `json:"reason"`
}

type PaymentEvent struct {
	ID             string        `json:"id"`
	IdempotencyKey string        `json:"idempotencyKey"`
	TenantID       string        `json:"tenantId"`
	Amount         int           `json:"amount"`
	Currency       string        `json:"currency"`
	Source         string        `json:"source"`
	Destination    string        `json:"destination"`
	Status         PaymentStatus `json:"status"`
	ReceivedAt     time.Time     `json:"receivedAt"`
}

type Query struct {
}

type Rule struct {
	ID        string     `json:"id"`
	TenantID  string     `json:"tenantId"`
	Name      string     `json:"name"`
	Version   int        `json:"version"`
	Action    RuleAction `json:"action"`
	Priority  int        `json:"priority"`
	Enabled   bool       `json:"enabled"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

type RuleContribution struct {
	RuleID   string `json:"ruleId"`
	RuleName string `json:"ruleName"`
	Matched  bool   `json:"matched"`
	Action   string `json:"action"`
	Reason   string `json:"reason"`
}

type RuleEvalResult struct {
	RuleID   string     `json:"ruleId"`
	RuleName string     `json:"ruleName"`
	Matched  bool       `json:"matched"`
	Action   RuleAction `json:"action"`
	Reason   string     `json:"reason"`
}

type SLOStatus struct {
	Service      string  `json:"service"`
	ErrorRate    float64 `json:"errorRate"`
	P50LatencyMs float64 `json:"p50LatencyMs"`
	P95LatencyMs float64 `json:"p95LatencyMs"`
	P99LatencyMs float64 `json:"p99LatencyMs"`
	Availability float64 `json:"availability"`
	Window       string  `json:"window"`
}

type SendNotificationInput struct {
	TenantID  string              `json:"tenantId"`
	Type      string              `json:"type"`
	Recipient string              `json:"recipient"`
	Channel   NotificationChannel `json:"channel"`
	Payload   string              `json:"payload"`
}

type SimulateRuleInput struct {
	TenantID       string     `json:"tenantId"`
	RuleID         string     `json:"ruleId"`
	Expression     string     `json:"expression"`
	Action         RuleAction `json:"action"`
	PaymentEventID string     `json:"paymentEventId"`
	Amount         int        `json:"amount"`
	Currency       string     `json:"currency"`
	Source         string     `json:"source"`
	Destination    string     `json:"destination"`
}

type Tenant struct {
	ID        string        `json:"id"`
	Name      string        `json:"name"`
	Status    TenantStatus  `json:"status"`
	CreatedAt time.Time     `json:"createdAt"`
	Config    *TenantConfig `json:"config"`
}

type TenantConfig struct {
	RuleSetID          string         `json:"ruleSetId"`
	WorkflowTemplateID string         `json:"workflowTemplateId"`
	FeatureFlags       []*FeatureFlag `json:"featureFlags"`
	Version            int            `json:"version"`
}

type TraceSpan struct {
	TraceID      string    `json:"traceId"`
	SpanID       string    `json:"spanId"`
	ParentSpanID string    `json:"parentSpanId"`
	Service      string    `json:"service"`
	Operation    string    `json:"operation"`
	DurationMs   int       `json:"durationMs"`
	Status       string    `json:"status"`
	StartTime    time.Time `json:"startTime"`
}

type TransitionInput struct {
	FromState    string `json:"fromState"`
	ToState      string `json:"toState"`
	RequiredRole string `json:"requiredRole"`
}

type TransitionResult struct {
	Allowed bool   `json:"allowed"`
	Reason  string `json:"reason"`
}

type UpdateCaseStatusInput struct {
	CaseID  string     `json:"caseId"`
	Status  CaseStatus `json:"status"`
	ActorID string     `json:"actorId"`
	Notes   string     `json:"notes"`
}

type UpdateNotificationPreferencesInput struct {
	TenantID  string              `json:"tenantId"`
	Channel   NotificationChannel `json:"channel"`
	EventType string              `json:"eventType"`
	Enabled   bool                `json:"enabled"`
	Config    string              `json:"config"`
}

type UpdateRuleInput struct {
	RuleID     string     `json:"ruleId"`
	TenantID   string     `json:"tenantId"`
	Expression string     `json:"expression"`
	Action     RuleAction `json:"action"`
	Priority   int        `json:"priority"`
	Enabled    bool       `json:"enabled"`
}

type UpdateTenantRuleConfigInput struct {
	TenantID  string `json:"tenantId"`
	RuleSetID string `json:"ruleSetId"`
}

type UpdateTenantWorkflowConfigInput struct {
	TenantID           string `json:"tenantId"`
	WorkflowTemplateID string `json:"workflowTemplateId"`
}

type UpdateWorkflowTemplateInput struct {
	TemplateID  string             `json:"templateId"`
	TenantID    string             `json:"tenantId"`
	States      []string           `json:"states"`
	Transitions []*TransitionInput `json:"transitions"`
}

type WorkflowGuard struct {
	Type      GuardType `json:"type"`
	Role      string    `json:"role"`
	Condition string    `json:"condition"`
}

type WorkflowTemplate struct {
	ID          string                `json:"id"`
	TenantID    string                `json:"tenantId"`
	Name        string                `json:"name"`
	Version     int                   `json:"version"`
	States      []string              `json:"states"`
	Transitions []*WorkflowTransition `json:"transitions"`
	CreatedAt   time.Time             `json:"createdAt"`
	UpdatedAt   time.Time             `json:"updatedAt"`
}

type WorkflowTransition struct {
	FromState    string           `json:"fromState"`
	ToState      string           `json:"toState"`
	RequiredRole string           `json:"requiredRole"`
	Guards       []*WorkflowGuard `json:"guards"`
}

type CasePriority string

const (
	CasePriorityLow      CasePriority = "LOW"
	CasePriorityMedium   CasePriority = "MEDIUM"
	CasePriorityHigh     CasePriority = "HIGH"
	CasePriorityCritical CasePriority = "CRITICAL"
)

var AllCasePriority = []CasePriority{
	CasePriorityLow,
	CasePriorityMedium,
	CasePriorityHigh,
	CasePriorityCritical,
}

func (e CasePriority) IsValid() bool {
	switch e {
	case CasePriorityLow, CasePriorityMedium, CasePriorityHigh, CasePriorityCritical:
		return true
	}
	return false
}

func (e CasePriority) String() string {
	return string(e)
}

func (e *CasePriority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CasePriority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CasePriority", str)
	}
	return nil
}

func (e CasePriority) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CasePriority) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CasePriority) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CaseStatus string

const (
	CaseStatusOpen      CaseStatus = "OPEN"
	CaseStatusInReview  CaseStatus = "IN_REVIEW"
	CaseStatusResolved  CaseStatus = "RESOLVED"
	CaseStatusEscalated CaseStatus = "ESCALATED"
)

var AllCaseStatus = []CaseStatus{
	CaseStatusOpen,
	CaseStatusInReview,
	CaseStatusResolved,
	CaseStatusEscalated,
}

func (e CaseStatus) IsValid() bool {
	switch e {
	case CaseStatusOpen, CaseStatusInReview, CaseStatusResolved, CaseStatusEscalated:
		return true
	}
	return false
}

func (e CaseStatus) String() string {
	return string(e)
}

func (e *CaseStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CaseStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CaseStatus", str)
	}
	return nil
}

func (e CaseStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CaseStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CaseStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GuardType string

const (
	GuardTypeRoleRequired GuardType = "ROLE_REQUIRED"
	GuardTypeCondition    GuardType = "CONDITION"
)

var AllGuardType = []GuardType{
	GuardTypeRoleRequired,
	GuardTypeCondition,
}

func (e GuardType) IsValid() bool {
	switch e {
	case GuardTypeRoleRequired, GuardTypeCondition:
		return true
	}
	return false
}

func (e GuardType) String() string {
	return string(e)
}

func (e *GuardType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GuardType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GuardType", str)
	}
	return nil
}

func (e GuardType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GuardType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GuardType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NotificationChannel string

const (
	NotificationChannelEmail   NotificationChannel = "EMAIL"
	NotificationChannelWebhook NotificationChannel = "WEBHOOK"
	NotificationChannelSLACk   NotificationChannel = "SLACK"
)

var AllNotificationChannel = []NotificationChannel{
	NotificationChannelEmail,
	NotificationChannelWebhook,
	NotificationChannelSLACk,
}

func (e NotificationChannel) IsValid() bool {
	switch e {
	case NotificationChannelEmail, NotificationChannelWebhook, NotificationChannelSLACk:
		return true
	}
	return false
}

func (e NotificationChannel) String() string {
	return string(e)
}

func (e *NotificationChannel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NotificationChannel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NotificationChannel", str)
	}
	return nil
}

func (e NotificationChannel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NotificationChannel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NotificationChannel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NotificationStatus string

const (
	NotificationStatusPending   NotificationStatus = "PENDING"
	NotificationStatusDelivered NotificationStatus = "DELIVERED"
	NotificationStatusFailed    NotificationStatus = "FAILED"
	NotificationStatusRetrying  NotificationStatus = "RETRYING"
)

var AllNotificationStatus = []NotificationStatus{
	NotificationStatusPending,
	NotificationStatusDelivered,
	NotificationStatusFailed,
	NotificationStatusRetrying,
}

func (e NotificationStatus) IsValid() bool {
	switch e {
	case NotificationStatusPending, NotificationStatusDelivered, NotificationStatusFailed, NotificationStatusRetrying:
		return true
	}
	return false
}

func (e NotificationStatus) String() string {
	return string(e)
}

func (e *NotificationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NotificationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NotificationStatus", str)
	}
	return nil
}

func (e NotificationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NotificationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NotificationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Outcome string

const (
	OutcomeApprove Outcome = "APPROVE"
	OutcomeFlag    Outcome = "FLAG"
	OutcomeReview  Outcome = "REVIEW"
	OutcomeBlock   Outcome = "BLOCK"
)

var AllOutcome = []Outcome{
	OutcomeApprove,
	OutcomeFlag,
	OutcomeReview,
	OutcomeBlock,
}

func (e Outcome) IsValid() bool {
	switch e {
	case OutcomeApprove, OutcomeFlag, OutcomeReview, OutcomeBlock:
		return true
	}
	return false
}

func (e Outcome) String() string {
	return string(e)
}

func (e *Outcome) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Outcome(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Outcome", str)
	}
	return nil
}

func (e Outcome) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Outcome) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Outcome) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PaymentStatus string

const (
	PaymentStatusReceived  PaymentStatus = "RECEIVED"
	PaymentStatusDuplicate PaymentStatus = "DUPLICATE"
	PaymentStatusRejected  PaymentStatus = "REJECTED"
)

var AllPaymentStatus = []PaymentStatus{
	PaymentStatusReceived,
	PaymentStatusDuplicate,
	PaymentStatusRejected,
}

func (e PaymentStatus) IsValid() bool {
	switch e {
	case PaymentStatusReceived, PaymentStatusDuplicate, PaymentStatusRejected:
		return true
	}
	return false
}

func (e PaymentStatus) String() string {
	return string(e)
}

func (e *PaymentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentStatus", str)
	}
	return nil
}

func (e PaymentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PaymentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PaymentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RuleAction string

const (
	RuleActionApprove RuleAction = "APPROVE"
	RuleActionFlag    RuleAction = "FLAG"
	RuleActionReview  RuleAction = "REVIEW"
	RuleActionBlock   RuleAction = "BLOCK"
)

var AllRuleAction = []RuleAction{
	RuleActionApprove,
	RuleActionFlag,
	RuleActionReview,
	RuleActionBlock,
}

func (e RuleAction) IsValid() bool {
	switch e {
	case RuleActionApprove, RuleActionFlag, RuleActionReview, RuleActionBlock:
		return true
	}
	return false
}

func (e RuleAction) String() string {
	return string(e)
}

func (e *RuleAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RuleAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RuleAction", str)
	}
	return nil
}

func (e RuleAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RuleAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RuleAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TenantStatus string

const (
	TenantStatusActive     TenantStatus = "ACTIVE"
	TenantStatusInactive   TenantStatus = "INACTIVE"
	TenantStatusOnboarding TenantStatus = "ONBOARDING"
)

var AllTenantStatus = []TenantStatus{
	TenantStatusActive,
	TenantStatusInactive,
	TenantStatusOnboarding,
}

func (e TenantStatus) IsValid() bool {
	switch e {
	case TenantStatusActive, TenantStatusInactive, TenantStatusOnboarding:
		return true
	}
	return false
}

func (e TenantStatus) String() string {
	return string(e)
}

func (e *TenantStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TenantStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TenantStatus", str)
	}
	return nil
}

func (e TenantStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TenantStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TenantStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
