apiVersion: v1
kind: Service
metadata:
  name: explanation
  namespace: risk-platform
spec:
  selector:
    app: explanation
  ports:
    - name: grpc
      port: 50060
      targetPort: 50060
    - name: metrics
      port: 9100
      targetPort: 9100
  type: ClusterIP
